// ═══════════════════════════════════════════════════════════════════
// Content Pack: Media (เสียง · 11 แผน · 165 ไฟล์)
// ═══════════════════════════════════════════════════════════════════
// แท็บ "📚 สื่อ/เครื่องมือ" ใน Teacher Dashboard
// folder ชี้ไปที่ lessons/physics3/sound/{แผนXX}/
// แต่ละแผนมี 15 ไฟล์: Infographic + Index + สื่อ 00-12
// ═══════════════════════════════════════════════════════════════════
window.KP_PLAN_MEDIA = {
  // ───────── แผน 1 · การเกิดและการเคลื่อนที่ของเสียง ─────────
  1: {
    folder: 'lessons/physics3/sound/แผน01_การเกิดและการเคลื่อนที่ของเสียง',
    title: 'แผน 1 — การเกิดเสียงและการเคลื่อนที่ของเสียง',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 1–2 (100 นาที) · หน่วยเสียง แผน 1',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 1', file:'00_Index_สื่อและเครื่องมือแผน1.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 1 (ฉบับสมบูรณ์)', file:'แผน1_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Demo Hook (Cymatics) (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "เสียงบนดวงจันทร์"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M1.1'],['m','M1.2'],['m','M1.3'],['m','M1.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M1.1'],['m','M1.2'],['m','M1.3'],['m','M1.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · คลื่นเสียง vs คลื่นน้ำ', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M1.1'],['m','M1.2'],['m','M1.3'],['m','M1.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน1.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F1 Four-tier · Pre + Post', file:'สื่อ05_F1_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F1-Pre + F1-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M1.1'],['m','M1.2'],['m','M1.3'],['m','M1.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F1 Pre/Post → ตาราง % Sound · Misconception M1.1–M1.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 2'
    ]
  },

  // ───────── แผน 2 · การกระจัดและคลื่นความดัน ─────────
  2: {
    folder: 'lessons/physics3/sound/แผน02_การกระจัดและคลื่นความดัน',
    title: 'แผน 2 — การกระจัดของอนุภาคและคลื่นความดัน',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 3–4 (100 นาที) · หน่วยเสียง แผน 2',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 2', file:'00_Index_สื่อและเครื่องมือแผน2.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 2 (ฉบับสมบูรณ์)', file:'แผน2_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Mystery + KWL (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "หูแก้วโดนอะไร"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M2.1'],['m','M2.2'],['m','M2.3'],['m','M2.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M2.1'],['m','M2.2'],['m','M2.3'],['m','M2.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · y(x) vs ΔP(x)', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M2.1'],['m','M2.2'],['m','M2.3'],['m','M2.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน2.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F2 Four-tier · Pre + Post', file:'สื่อ05_F2_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F2-Pre + F2-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M2.1'],['m','M2.2'],['m','M2.3'],['m','M2.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F2 Pre/Post → ตาราง % Sound · Misconception M2.1–M2.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 3'
    ]
  },

  // ───────── แผน 3 · อัตราเร็วของเสียง ─────────
  3: {
    folder: 'lessons/physics3/sound/แผน03_อัตราเร็วของเสียงและอุณหภูมิ',
    title: 'แผน 3 — อัตราเร็วของเสียงและผลของอุณหภูมิ',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 5–6 (100 นาที) · หน่วยเสียง แผน 3',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 3', file:'00_Index_สื่อและเครื่องมือแผน3.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 3 (ฉบับสมบูรณ์)', file:'แผน3_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Real-life Case (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "ห้องเย็น vs ห้องร้อน"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M3.1'],['m','M3.2'],['m','M3.3'],['m','M3.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M3.1'],['m','M3.2'],['m','M3.3'],['m','M3.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · v ในตัวกลางต่าง ๆ', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M3.1'],['m','M3.2'],['m','M3.3'],['m','M3.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน3.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F3 Four-tier · Pre + Post', file:'สื่อ05_F3_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F3-Pre + F3-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M3.1'],['m','M3.2'],['m','M3.3'],['m','M3.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F3 Pre/Post → ตาราง % Sound · Misconception M3.1–M3.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 4'
    ]
  },

  // ───────── แผน 4 · พฤติกรรมของคลื่นเสียง ─────────
  4: {
    folder: 'lessons/physics3/sound/แผน04_พฤติกรรมของคลื่นเสียง',
    title: 'แผน 4 — พฤติกรรมของคลื่นเสียง: สะท้อน หักเห เลี้ยวเบน แทรกสอด',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 7–8 (100 นาที) · หน่วยเสียง แผน 4',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 4', file:'00_Index_สื่อและเครื่องมือแผน4.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 4 (ฉบับสมบูรณ์)', file:'แผน4_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Anticipation Guide (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "ทำไมได้ยินรอบมุมตึก"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M4.1'],['m','M4.2'],['m','M4.3'],['m','M4.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M4.1'],['m','M4.2'],['m','M4.3'],['m','M4.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · 4 พฤติกรรมของคลื่นเสียง', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M4.1'],['m','M4.2'],['m','M4.3'],['m','M4.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน4.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F4 Four-tier · Pre + Post', file:'สื่อ05_F4_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F4-Pre + F4-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M4.1'],['m','M4.2'],['m','M4.3'],['m','M4.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F4 Pre/Post → ตาราง % Sound · Misconception M4.1–M4.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 5'
    ]
  },

  // ───────── แผน 5 · ความเข้มและระดับเสียง ─────────
  5: {
    folder: 'lessons/physics3/sound/แผน05_ความเข้มและระดับเสียง',
    title: 'แผน 5 — ความเข้มเสียงและระดับเสียง (เดซิเบล)',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 9–10 (100 นาที) · หน่วยเสียง แผน 5',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 5', file:'00_Index_สื่อและเครื่องมือแผน5.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 5 (ฉบับสมบูรณ์)', file:'แผน5_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Photo Stimulus (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "ลำโพงปาร์ตี้"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M5.1'],['m','M5.2'],['m','M5.3'],['m','M5.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M5.1'],['m','M5.2'],['m','M5.3'],['m','M5.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · I และ β ในชีวิตจริง', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M5.1'],['m','M5.2'],['m','M5.3'],['m','M5.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน5.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F5 Four-tier · Pre + Post', file:'สื่อ05_F5_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F5-Pre + F5-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M5.1'],['m','M5.2'],['m','M5.3'],['m','M5.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F5 Pre/Post → ตาราง % Sound · Misconception M5.1–M5.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 6'
    ]
  },

  // ───────── แผน 6 · การได้ยินและมลพิษเสียง ─────────
  6: {
    folder: 'lessons/physics3/sound/แผน06_การได้ยินและมลพิษทางเสียง',
    title: 'แผน 6 — การได้ยินและมลพิษทางเสียง',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 11–12 (100 นาที) · หน่วยเสียง แผน 6',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 6', file:'00_Index_สื่อและเครื่องมือแผน6.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 6 (ฉบับสมบูรณ์)', file:'แผน6_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Video Analysis (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "อายุกับการได้ยิน"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M6.1'],['m','M6.2'],['m','M6.3'],['m','M6.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M6.1'],['m','M6.2'],['m','M6.3'],['m','M6.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · ช่วง f ของสิ่งมีชีวิต', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M6.1'],['m','M6.2'],['m','M6.3'],['m','M6.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน6.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F6 Four-tier · Pre + Post', file:'สื่อ05_F6_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F6-Pre + F6-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M6.1'],['m','M6.2'],['m','M6.3'],['m','M6.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F6 Pre/Post → ตาราง % Sound · Misconception M6.1–M6.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 7'
    ]
  },

  // ───────── แผน 7 · Pitch + Timbre ─────────
  7: {
    folder: 'lessons/physics3/sound/แผน07_ระดับสูงต่ำและคุณภาพเสียง',
    title: 'แผน 7 — ระดับสูง-ต่ำของเสียง (Pitch) และคุณภาพเสียง (Timbre)',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 13–14 (100 นาที) · หน่วยเสียง แผน 7',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 7', file:'00_Index_สื่อและเครื่องมือแผน7.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 7 (ฉบับสมบูรณ์)', file:'แผน7_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Demo + POE (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "Voice ID"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M7.1'],['m','M7.2'],['m','M7.3'],['m','M7.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M7.1'],['m','M7.2'],['m','M7.3'],['m','M7.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · Pitch · Loudness · Timbre', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M7.1'],['m','M7.2'],['m','M7.3'],['m','M7.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน7.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F7 Four-tier · Pre + Post', file:'สื่อ05_F7_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F7-Pre + F7-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M7.1'],['m','M7.2'],['m','M7.3'],['m','M7.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F7 Pre/Post → ตาราง % Sound · Misconception M7.1–M7.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 8'
    ]
  },

  // ───────── แผน 8 · คลื่นนิ่ง + Resonance Tube ─────────
  8: {
    folder: 'lessons/physics3/sound/แผน08_คลื่นนิ่งและการสั่นพ้องในท่อ',
    title: 'แผน 8 — คลื่นนิ่งของเสียงและการสั่นพ้องในท่อปลายปิด',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 15–16 (100 นาที) · หน่วยเสียง แผน 8',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 8', file:'00_Index_สื่อและเครื่องมือแผน8.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 8 (ฉบับสมบูรณ์)', file:'แผน8_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Real Object (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "เป่าขวด"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M8.1'],['m','M8.2'],['m','M8.3'],['m','M8.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M8.1'],['m','M8.2'],['m','M8.3'],['m','M8.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · Modes ของท่อปลายปิด/เปิด', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M8.1'],['m','M8.2'],['m','M8.3'],['m','M8.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน8.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F8 Four-tier · Pre + Post', file:'สื่อ05_F8_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F8-Pre + F8-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M8.1'],['m','M8.2'],['m','M8.3'],['m','M8.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F8 Pre/Post → ตาราง % Sound · Misconception M8.1–M8.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 9'
    ]
  },

  // ───────── แผน 9 · บีต (Beat) ─────────
  9: {
    folder: 'lessons/physics3/sound/แผน09_บีต',
    title: 'แผน 9 — บีต (Beat)',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 17–18 (100 นาที) · หน่วยเสียง แผน 9',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 9', file:'00_Index_สื่อและเครื่องมือแผน9.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 9 (ฉบับสมบูรณ์)', file:'แผน9_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Story Hook (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "จูนกีตาร์"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M9.1'],['m','M9.2'],['m','M9.3'],['m','M9.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M9.1'],['m','M9.2'],['m','M9.3'],['m','M9.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · Beat ในสถานการณ์ต่าง ๆ', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M9.1'],['m','M9.2'],['m','M9.3'],['m','M9.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน9.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F9 Four-tier · Pre + Post', file:'สื่อ05_F9_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F9-Pre + F9-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M9.1'],['m','M9.2'],['m','M9.3'],['m','M9.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F9 Pre/Post → ตาราง % Sound · Misconception M9.1–M9.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 10'
    ]
  },

  // ───────── แผน 10 · Doppler + Shock Wave ─────────
  10: {
    folder: 'lessons/physics3/sound/แผน10_ดอปเพลอร์และคลื่นกระแทก',
    title: 'แผน 10 — ปรากฏการณ์ดอปเพลอร์และคลื่นกระแทก',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 19–20 (100 นาที) · หน่วยเสียง แผน 10',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 10', file:'00_Index_สื่อและเครื่องมือแผน10.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 10 (ฉบับสมบูรณ์)', file:'แผน10_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Comparison (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "คนขับรถพยาบาล"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M10.1'],['m','M10.2'],['m','M10.3'],['m','M10.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M10.1'],['m','M10.2'],['m','M10.3'],['m','M10.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · 4 กรณีของ Doppler', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M10.1'],['m','M10.2'],['m','M10.3'],['m','M10.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน10.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F10 Four-tier · Pre + Post', file:'สื่อ05_F10_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F10-Pre + F10-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M10.1'],['m','M10.2'],['m','M10.3'],['m','M10.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F10 Pre/Post → ตาราง % Sound · Misconception M10.1–M10.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน 11'
    ]
  },

  // ───────── แผน 11 · การประยุกต์ + Posttest ─────────
  11: {
    folder: 'lessons/physics3/sound/แผน11_การประยุกต์ใช้ความรู้เรื่องเสียง',
    title: 'แผน 11 — การประยุกต์ใช้ความรู้เรื่องเสียง + Posttest ทั้งบท',
    meta: 'ว32203 ฟิสิกส์ 3 · ม.5 · คาบ 21–22 (100 นาที) · หน่วยเสียง แผน 11',
    sections: [
      { title: '🗺 แผนภาพรวม', items: [
        { cls:'info', no:'00', t:'Index สื่อและเครื่องมือ แผน 11', file:'00_Index_สื่อและเครื่องมือแผน11.html',
          d:'แผนภาพรวมการสอน · 5E+POE · media map · vPA 8 ตัวชี้วัด', chips:[] },
        { cls:'info', no:'IG', t:'Infographic แผน 11 (ฉบับสมบูรณ์)', file:'แผน11_Infographic.html',
          d:'K/P/A · 5E+POE 11 ขั้น · ACT+GOAL · vPA · Timeline 100 นาที', chips:[] }
      ]},
      { title: '🚀 เกริ่นนำและกิจกรรมหลัก', items: [
        { cls:'e1', no:'0', t:'🚀 เกริ่นนำ + ทบทวนความรู้เดิม', file:'สื่อ00_Engage_เกริ่นนำ.html',
          d:'ความรู้เดิม + Engage type: Gallery Walk (ไม่ซ้ำกับแผนอื่น)',
          meta:'15-20 นาทีแรก · ก่อน E1',
          chips:[['','Activate Prior'],['w','วPA 2 ⭐']] },
        { cls:'e1', no:'01', t:'Concept Cartoon "Sound Detective"', file:'สื่อ01_ConceptCartoon.html',
          d:'3 ตัวละครถกเถียง · กระตุ้น POE-P',
          meta:'E1 Engage · 15 นาที',
          chips:[['m','M11.1'],['m','M11.2'],['m','M11.3'],['m','M11.4']] },
        { cls:'e2', no:'02', t:'POE-01 ใบบันทึก (ทดลองจริง)', file:'สื่อ02_POE-01_ใบบันทึก.html',
          d:'P + O (กิจกรรมทดลอง + ตารางบันทึก) + E + Misconception 4 ตัว · canvas วาด',
          meta:'E1 → E3 · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['m','M11.1'],['m','M11.2'],['m','M11.3'],['m','M11.4']] },
        { cls:'e4', no:'03', t:'Matrix Table · Synthesis Map ภาพรวมหน่วยเสียง', file:'สื่อ03_MatrixTable.html',
          d:'ตารางเปรียบเทียบ · สรุปแนวคิดหลักของแผน',
          meta:'E3-E4 · 10 นาที',
          chips:[['k','K2'],['p','P2']] },
        { cls:'e4', no:'04', t:'Spot the Error · 4 ข้อ', file:'สื่อ04_SpotTheError.html',
          d:'หาที่ผิด + แก้ + อ้างหลักฐาน · มีเฉลย',
          meta:'E4 Elaborate · 10 นาที',
          chips:[['k','K2'],['p','P2'],['m','M11.1'],['m','M11.2'],['m','M11.3'],['m','M11.4']] },
        { cls:'e4', no:'11', t:'ใบงาน Calc · Math Builder (5 ข้อ)', file:'สื่อ11_Calc_ใบงาน11.1.html',
          d:'โจทย์คำนวณ · canvas วาดวิธีคิด · self-check · ไล่ระดับ',
          meta:'E4 Elaborate · 15-20 นาที',
          chips:[['k','K2'],['p','P1']] },
        { cls:'e4', no:'12', t:'แบบฝึกหัด 12 ข้อ', file:'สื่อ12_Exercise_12ข้อ.html',
          d:'4 MCQ + 4 Calc + 2 Short + 2 Application · มีเฉลย · เป้า ≥ 9/12',
          meta:'การบ้าน / E4 · 30-40 นาที',
          chips:[['k','K2'],['p','P1'],['p','P2']] }
      ]},
      { title: '📊 เครื่องมือวัดและประเมิน', items: [
        { cls:'ft', no:'05', t:'F11 Four-tier · Pre + Post', file:'สื่อ05_F11_Fourtier_PrePost.html',
          d:'3 ข้อ × 4-tier · เก็บ Sound/Misconception/Guessing/No-K · เฉลยสำหรับครู',
          meta:'F11-Pre + F11-Post · 5\' × 2',
          chips:[['k','K1'],['k','K2'],['m','M11.1'],['m','M11.2'],['m','M11.3'],['m','M11.4'],['w','วPA 2,6']] },
        { cls:'tlc', no:'06', t:'TL-01 · Traffic Light Card', file:'สื่อ06_TL-01_TrafficLight.html',
          d:'บัตร 🟢🟡🔴 ประเมินตนเอง ก่อน-หลังคาบ',
          meta:'TLC-Pre + Post · 3\' × 2',
          chips:[['a','A1'],['w','วPA 4,7']] },
        { cls:'mj', no:'07', t:'MJ-01 · Metacognitive Journal 3-2-1', file:'สื่อ07_MJ-01_MetacognitiveJournal.html',
          d:'3 เข้าใจ · 2 น่าสนใจ · 1 สงสัย · Feed-forward สู่แผนถัดไป',
          meta:'MJ · 2-3 นาที',
          chips:[['a','A2'],['w','วPA 6,8']] },
        { cls:'ob', no:'08', t:'OB-01 · แบบสังเกตพฤติกรรม', file:'สื่อ08_OB-01_แบบสังเกตพฤติกรรม.html',
          d:'ครูสังเกตด้าน P · A · สมรรถนะ · 8 คน/กลุ่ม',
          meta:'ครู · ตลอดคาบ',
          chips:[['p','P1'],['p','P2'],['a','A1'],['w','วPA 4,7']] },
        { cls:'rubric', no:'09', t:'POE Rubric (0-3)', file:'สื่อ09_POE_Rubric.html',
          d:'เกณฑ์ประเมิน P-O-E + Misconception Reflection',
          meta:'ครู · หลังคาบ',
          chips:[['p','P1'],['p','P2'],['w','วPA 3,5']] },
        { cls:'ft', no:'10', t:'Exit Ticket · 5 ข้อ', file:'สื่อ10_ExitTicket.html',
          d:'คำถามสั้น 5 ข้อ · ตอบ 1-2 ประโยค · ปลายคาบ',
          meta:'ก่อนเลิกคาบ · 5 นาที',
          chips:[['k','K1'],['k','K2']] }
      ]}
    ],
    linkOut: [
      'F11 Pre/Post → ตาราง % Sound · Misconception M11.1–M11.4 · Normalized gain',
      'POE-01 + Rubric → คะแนน POE รายบุคคล · เป้า ≥ 2.0',
      'TL-01 → อัตราบัตรเขียวก่อน-หลัง · เป้า ≥ 60%',
      'MJ-01 → คำถามเด่นเป็น Hook แผน ถัดไป'
    ]
  },

};
