/* ===== COSMOS LOG · EP08 CONFIG · "Genesis Again · Season Finale" =====
 * 28 หน้า · 4 องก์ · 17 keys S1 keyring · 8 mystery box · Boss = GENESIS FORGE 4 epoch
 * Curriculum: ว 7.2 ม.6/3-5 (สังเคราะห์ทั้งซีซัน + Big Bang Cosmology · ตำรา สสวท.)
 */
window.EP_CONFIG = {
  id: 'ep08',
  title: 'Genesis Again · จุดเริ่มต้นอีกครั้ง',
  badge: '🏆 COMMANDER',
  rank: 'COMMANDER',
  duration: 140,
  curriculum: 'ว 7.2 ม.6/3-5 (Big Bang + summative ทั้งซีซัน)',

  /* ===== 28 หน้า · 4 องก์ ===== */
  pages: [
    /* ACT A · ARRIVAL @ t=0 */
    { id:'p00', title:'Cover · Warp Jump',          file:'p00-cover.html',           act:'A' },
    { id:'p01', title:'Pretest 10 ข้อ summative',    file:'p01-pretest.html',         act:'A' },
    { id:'p02', title:'The Void · quark soup',      file:'p02-the-void.html',        act:'A' },
    { id:'p03', title:'CMB Shower · 2.73K',          file:'p03-cmb-shower.html',      act:'A' },
    { id:'p04', title:'Mission Brief · ดร.ฮับเบิล',  file:'p04-mission-brief.html',   act:'A' },

    /* ACT B · TIMELINE OF GENESIS */
    { id:'p05', title:'Inflation · 10⁻³⁶ s',         file:'p05-inflation.html',       act:'B' },
    { id:'p06', title:'Nucleosynthesis · 3 นาที',    file:'p06-nucleosynthesis.html', act:'B' },
    { id:'p07', title:'Recombination · 380 kyr',    file:'p07-recombination.html',   act:'B' },
    { id:'p08', title:'First Stars · 200 Myr',      file:'p08-first-stars.html',     act:'B' },
    { id:'p09', title:'Galaxies · 1 Gyr',           file:'p09-galaxies.html',        act:'B' },
    { id:'p10', title:"⭐ Father's Arrival",         file:'p10-fathers-arrival.html', act:'B' },
    { id:'p11', title:"Father's Truth · 2008",      file:'p11-fathers-truth.html',   act:'B' },
    { id:'p12', title:"Hubble's Law · v=H₀D",        file:'p12-hubbles-law.html',     act:'B' },

    /* ACT C · VOID PRIME REVEALED */
    { id:'p13', title:'VOID Prime ปรากฏ',           file:'p13-prime-appears.html',   act:'C' },
    { id:'p14', title:'Anti-Genesis Engine · 4 จุด', file:'p14-prime-plan.html',      act:'C' },
    { id:'p15', title:'Disable 1 · Inflation',      file:'p15-disable-1.html',       act:'C' },
    { id:'p16', title:'Disable 2 · CMB',             file:'p16-disable-2.html',       act:'C' },
    { id:'p17', title:'Disable 3 · Fusion',          file:'p17-disable-3.html',       act:'C' },
    { id:'p18', title:'Disable 4 · Galaxies',        file:'p18-disable-4.html',       act:'C' },
    { id:'p19', title:'Hall of Spinoff (EP07)',     file:'p19-hall-of-spinoff.html', act:'C' },
    { id:'p20', title:'Hall of Knowledge (EP01-06)',file:'p20-hall-of-knowledge.html',act:'C' },

    /* ACT D · GENESIS DEFENSE + FAREWELL */
    { id:'p21', title:"⭐ Father's Choice · Reset/Preserve", file:'p21-fathers-choice.html', act:'D' },
    { id:'p22', title:'Boss Prep · Forge GENESIS LANCE',     file:'p22-boss-prep.html',     act:'D' },
    { id:'p22b',title:'🎯 Recall · Big Bang + Hubble',        file:'p22b-recall.html',       act:'D' },
    { id:'p23', title:'🔥 BOSS · GENESIS FORGE',              file:'p23-boss.html',          act:'D' },
    { id:'p24', title:'Ending A · PRESERVE',                  file:'p24-ending-preserve.html', act:'D' },
    { id:'p25', title:'🌟 Ending Reset Route',                file:'p25-ending-reset.html',   act:'D' },
    { id:'p26', title:'Farewell · 4 NPC ลาจาก',               file:'p26-farewell.html',       act:'D' },
    { id:'p26b', title:'🏆 Hall of Fame · ทีมชนะ EP08 (Season Final)', file:'p26b-halloffame.html', act:'D' },
    { id:'p27', title:'Journal · 🏆 COMMANDER + S2',         file:'p27-journal.html',        act:'D' }
  ],

  /* ===== Misconceptions M-FINAL-1..7 ===== */
  misconceptions: [
    { id:'M-FINAL-1', text:'บิกแบงคือระเบิดในที่ว่าง',          counter:'ที่ว่างเองขยายตัว · ไม่ใช่ระเบิดในที่ว่าง' },
    { id:'M-FINAL-2', text:'เอกภพมีขอบ',                        counter:'ไม่มีขอบ · ขยายทุกทิศ' },
    { id:'M-FINAL-3', text:'เห็นไกลขึ้น = ภาพปัจจุบัน',          counter:'เห็นไกล = เห็นอดีต · แสงต้องเดินทาง' },
    { id:'M-FINAL-4', text:'ฮับเบิลค่าคงที่ตลอดเวลา',           counter:'จริงคือเปลี่ยนตามเวลาเอกภพ' },
    { id:'M-FINAL-5', text:'ธาตุหนักเกิดในบิกแบง',                counter:'ส่วนใหญ่เกิดในซูเปอร์โนวา · หลังบิกแบง' },
    { id:'M-FINAL-6', text:'เทคโนฯ อวกาศไม่คุ้ม',                counter:'ทุกอย่างที่ใช้กู้บิกแบงมาจาก spinoff' },
    { id:'M-FINAL-7', text:'เอกภพเริ่มจากไม่มีอะไร',             counter:'เริ่มจาก quantum fluctuation' }
  ],

  /* ===== Pretest 10 ข้อ summative ===== */
  // Pre-test 5 ข้อ · summative ทั้งซีซัน · misconception M-FINAL + วัตถุประสงค์ K
  pretest: [
    { q:'บิกแบง (Big Bang) คืออะไร?',
      opts:['ระเบิดในที่ว่างขนาดใหญ่','การขยายตัวของกาลอวกาศ (spacetime) เอง','การยุบตัวของดาวฤกษ์ขนาดยักษ์','การปะทะของกาแล็กซีสองอัน'], answer:1, tag:'M-FINAL-1' },
    { q:'เอกภพมีขอบหรือไม่?',
      opts:['มี · เป็นกำแพงด้านนอก','ไม่มี · ขยายตัวทุกทิศพร้อมกัน','มี แต่หามองไม่เจอ','มีเฉพาะด้านเดียว'], answer:1, tag:'M-FINAL-2' },
    { q:'เมื่อเรามองดาวที่อยู่ห่าง 13 พันล้านปีแสง · เราเห็นอะไร?',
      opts:['ภาพปัจจุบันของดาว','ภาพอนาคตของดาว','ภาพอดีต ~13 พันล้านปีก่อน','ภาพเมื่อ 1 ปีก่อน'], answer:2, tag:'M-FINAL-3' },
    { q:'กฎของฮับเบิล (Hubble\'s law) มีรูปสมการใด?',
      opts:['v = H₀D','E = mc²','F = ma','PV = nRT'], answer:0, tag:'M-FINAL-4' },
    { q:'ธาตุหนัก (Fe, Au, U) ส่วนใหญ่เกิดที่ไหน?',
      opts:['ในบิกแบง 3 นาทีแรก','ในซูเปอร์โนวาของดาวมวลมาก','ในแกนของดวงอาทิตย์','ในกาแล็กซีไกลเท่านั้น'], answer:1, tag:'M-FINAL-5' }
  ],

  /* ===== 8 Mystery Box · ตำแหน่งตรง research checkpoint ===== */
  mysteryBoxes: [
    { id:'MB1', page:'p01', checkpoint:'summative-pretest',
      reward:{ coin:8 }, cosmetic:'Genesis Pretest Seal',
      prompt:'หลังทำ pretest · เธอเดาว่าตัวเองรู้กี่ข้อ?', delay:800 },
    { id:'MB2', page:'p07', checkpoint:'cmb-mastery',
      reward:{ coin:10, energy:2 }, cosmetic:'CMB Halo',
      prompt:'CMB 2.73K มาจากเหตุการณ์ไหน · อธิบายสั้นๆ' },
    { id:'MB3', page:'p10', checkpoint:'drama-father',
      reward:{ coin:12 }, cosmetic:"Father's Memory",
      prompt:'ถ้าเธอเป็นโบลท์ · เห็นพ่อโผล่จาก fluctuation · ความรู้สึกแรกคือ?' },
    { id:'MB4', page:'p12', checkpoint:'hubbles-law-mastery',
      reward:{ coin:10 }, cosmetic:'Hubble Lens',
      prompt:'v = H₀D บอกเราอะไรเกี่ยวกับเอกภพที่กำลังขยาย?' },
    { id:'MB5', page:'p15', checkpoint:'epoch-1-mastery',
      reward:{ coin:10, energy:2 }, cosmetic:'Inflation Wave',
      prompt:'หลัง stabilize inflation · เธอใช้ key อะไรบ้าง · ทำไม?' },
    { id:'MB6', page:'p20', checkpoint:'s1-knowledge-recall',
      reward:{ coin:14, energy:3 }, cosmetic:'S1 Crown',
      prompt:'ใน Hall of Knowledge · EP ไหนที่เธอจำได้ดีที่สุด · ทำไม?' },
    { id:'MB7', page:'p21', checkpoint:'choice-ethics',
      reward:{ coin:15 }, cosmetic:'Ethics Pendant',
      prompt:'Reset (พ่อกลับ) vs Preserve (จักรวาลรอด) · เลือกอะไร · เพราะ?' },
    { id:'MB8', page:'p27', checkpoint:'summative-posttest',
      reward:{ coin:20, energy:5 }, cosmetic:'Commander Sash',
      prompt:'1 ประโยคที่อยากเล่าให้น้องฟังเกี่ยวกับบิกแบง + ทั้งซีซัน' }
  ],

  /* ===== Boss · GENESIS FORGE · 4 epoch ===== */
  boss: {
    id:'genesis-forge',
    name:'GENESIS FORGE · Final Showdown',
    durationMin: 8,
    hpStart: 12,
    phases: [
      { id:1, key:'inflation',   need:6,  cats:['bigbang','stellar'],          color:'#ff6ab8',
        taunt:'ฉันจะหยุด inflation · จักรวาลจะยุบกลับ',
        victory:'INFLATION STABILIZED · เอกภพขยาย 10²⁶ เท่า' },
      { id:2, key:'nucleosynth', need:12, cats:['stellar','sun'],              color:'#ff8a3d',
        taunt:'ไม่มีฟิวชัน · ไม่มีดาวฤกษ์',
        victory:'FIRST NUCLEI FORMED · H · He · Li' },
      { id:3, key:'cmb',         need:3,  cats:['bigbang','stellar','tech'],   color:'#ffd84a',
        taunt:'จักรวาลจะขุ่นมัวตลอดกาล',
        victory:'CMB RELEASED · 2.73K · FIRST STARS IGNITED' },
      { id:4, key:'galaxies',    need:8,  cats:['solar','tech'],               color:'#6a3aff',
        taunt:'ฉันจะกระจาย dark matter · ไม่มีกาแล็กซี',
        victory:'GALAXIES BORN · STRUCTURE LOCKED' }
    ],
    finisherKeyMin: 12,
    achievements: [
      { id:'ach_witness',      icon:'🌌', name:'BIG BANG WITNESS',  need:'จบ pretest' },
      { id:'ach_guardian',     icon:'⏰', name:'TIMELINE GUARDIAN', need:'ผ่าน 4 epoch' },
      { id:'ach_nuclear',      icon:'🔬', name:'NUCLEAR SCIENTIST', need:'epoch 2 perfect' },
      { id:'ach_starforger',   icon:'💫', name:'STAR FORGER',       need:'epoch 3 perfect' },
      { id:'ach_galaxy',       icon:'🌠', name:'GALAXY ARCHITECT',  need:'epoch 4 perfect' },
      { id:'ach_voidslayer',   icon:'👁️', name:'VOID SLAYER',       need:'finisher GENESIS LANCE' },
      { id:'ach_son',          icon:'👨‍✈️', name:'SON RETURNED',      need:'จบ p10 + p21' },
      { id:'ach_commander',    icon:'🏆', name:'COMMANDER',         need:'จบ p27' },
      { id:'ach_infinite',     icon:'♾️', name:'INFINITE LEARNER',  need:'ใช้ครบ 17 keys' },
      { id:'ach_scholar',      icon:'🎓', name:'SCHOLAR',           need:'posttest ≥ 80%' },
      { id:'ach_nohint',       icon:'🛡️', name:'NO HINT FINALE',    need:'boss · ไม่ใช้ hint' },
      { id:'ach_speedrun',     icon:'⚡', name:'SPEEDRUN',          need:'boss < 5 นาที' }
    ]
  },

  /* ===== Story Spine · ทุกหน้า ===== */
  story: {
    p00: { objective:'Warp Jump 13.8 พันล้านปี', npc:'',
      now:'ทีมเปิด warp ของพ่อ · พิกัด t=0 · เด้งออกที่ "จุดที่ยังไม่มีอะไร"',
      next:'อยู่รอดให้ได้ · pretest ก่อนภารกิจ' },
    p01: { objective:'Baseline summative', npc:'พ่ออารยา',
      prev:'warp jump สำเร็จ · ระบบ AI เก็บข้อมูล',
      line:'ก่อนเข้าสนามรบสุดท้าย · ขอ baseline ทั้งซีซัน 10 ข้อ',
      now:'pretest 10 ข้อ summative · M-FINAL-1..7',
      next:'เคนวิ่งไปดูภายนอก' },
    p02: { objective:'รู้จัก quark soup', npc:'เคน',
      prev:'pretest เก็บแล้ว · เห็น "จุดที่ยังไม่มีอะไร"',
      line:'ดู! ไม่มีดาว · ไม่มีสสาร · มีแค่ quark พร่ามัวเท่านั้น',
      now:'อ่าน quark soup state · เผชิญ misconception M-FINAL-7',
      next:'ทำไมยังเห็น CMB · ทั้งที่ยังไม่มีดาว?' },
    p03: { objective:'เข้าใจ CMB', npc:'อารยา',
      prev:'พบ quark soup · งงว่า CMB มาจากไหน',
      line:'CMB คือเสียงสะท้อนจาก 380,000 ปีหลังบิกแบง · เรากำลังจะไปเห็นมันเกิดจริงๆ',
      now:'เห็น CMB shower 2.73K + เผชิญ M-FINAL-3',
      next:'พ่ออารยา + ดร.ฮับเบิลตั้งภารกิจ' },
    p04: { objective:'รับภารกิจสุดท้าย', npc:'พ่ออารยา + ดร.ฮับเบิล',
      prev:'เข้าใจ CMB · เห็นเงาดำของ VOID Prime ที่ขอบ',
      line:'VOID Prime วาง Anti-Genesis Engine 4 จุด · เธอต้อง stabilize ทุก epoch',
      now:'ดร.ฮับเบิลเปิดตัว (Mentor reveal · จาก Bible) · brief 4 epoch',
      next:'เริ่มเดินไทม์ไลน์ Inflation' },
    p05: { objective:'เรียน Inflation', npc:'ดร.ฮับเบิล',
      prev:'รับภารกิจ · ก้าวแรกในไทม์ไลน์',
      line:'10⁻³⁶ วินาที · อวกาศขยาย 10²⁶ เท่า · นั่นคือสาเหตุที่เอกภพดูราบเรียบ',
      now:'ทดลอง slider · ขยาย fluctuation จนได้ 10²⁶ เท่า',
      next:'หลัง inflation · เกิดธาตุครั้งแรก' },
    p06: { objective:'นิวเคลียสแรก', npc:'อารยา',
      prev:'inflation จบ · จักรวาลร้อนเหลือ T~10⁹ K',
      line:'3 นาที · proton + neutron รวมเป็น H · He · Li · ไม่มีธาตุหนัก!',
      now:'ลาก p+n → H/He/Li · M-FINAL-5 (ธาตุหนักไม่ได้เกิดที่นี่)',
      next:'อีก 380,000 ปีกว่าจะเกิดอะตอม' },
    p07: { objective:'CMB ปลดปล่อย', npc:'เคน',
      prev:'นิวเคลียสเกิดแล้ว · แต่จักรวาลยังขุ่นด้วย plasma',
      line:'380,000 ปีถัดมา · electron จับกับ nucleus = อะตอม · CMB หลุดออกมา',
      now:'จำลอง recombination · ก่อน/หลัง · M-FINAL-3 (เห็นไกล=เห็นอดีต)',
      next:'อีก 200 ล้านปีกว่าจะมีดาวดวงแรก' },
    p08: { objective:'ดาวดวงแรก', npc:'ดร.ฮับเบิล',
      prev:'CMB หลุด · จักรวาลใส · แต่ดำสนิท · ไม่มีดาว',
      line:'แรงโน้มถ่วงดึง gas เป็นกระจุก · จุดประกายฟิวชัน · ดาวดวงแรกติดไฟ',
      now:'จำลอง gravity collapse → first stars',
      next:'ดาวรวมกันเป็นกาแล็กซี' },
    p09: { objective:'กาแล็กซีก่อตัว', npc:'อารยา',
      prev:'first stars ติดไฟ · ดึงดูดกัน',
      line:'1 พันล้านปี · ดาวรวมเป็นกาแล็กซี · dark matter เป็นโครงคงตัว',
      now:'จัด dark matter scaffold + galactic structure · M-FINAL-2',
      next:'มีบางอย่างเคลื่อนไหวใน fluctuation...' },
    p10: { objective:'⭐ พ่อปรากฏ', npc:'พ่อโบลท์ · E. Hara',
      prev:'กาแล็กซีก่อตัว · ขอบจักรวาลเริ่มสว่าง',
      line:'(เงาคนโผล่จาก fluctuation)\n"ลูก...พ่อรอเธอที่นี่นาน 13.8 พันล้านปี"',
      now:'ฉาก emotional · โบลท์เจอพ่อตัวจริงครั้งแรกตั้งแต่ 2008',
      next:'พ่อจะเล่าความจริง' },
    p11: { objective:'รู้ความจริง', npc:'พ่อโบลท์',
      prev:'พ่อโผล่ออกจาก fluctuation · โบลท์เกือบไม่เชื่อ',
      line:'ปี 2008 · พ่อถูก VOID จู่โจม · พลัดเข้า warp · ติดที่ t=0 · เป็นผู้พิทักษ์บิกแบง',
      now:'เผยเรื่องราวพ่อ + drone จาก EP07 · ปิด arc ปริศนา',
      next:'ดร.ฮับเบิลสอนคำนวณตำแหน่ง Anti-Genesis Engine' },
    p12: { objective:"เรียน Hubble's Law", npc:'ดร.ฮับเบิล',
      prev:'รู้แล้วว่าพ่อเป็น sentinel · ต้องหา Engine 4 จุด',
      line:'v = H₀D · ใช้กฎฮับเบิลคำนวณว่า Engine แต่ละตัวอยู่ที่ไหนในไทม์ไลน์',
      now:'ฝึกคำนวณ v · D · อายุเอกภพ · M-FINAL-4',
      next:'VOID Prime จะปรากฏตัว' },
    p13: { objective:'เผชิญ VOID Prime', npc:'VOID Prime',
      prev:'รู้พิกัด Engine · กำลังเข้าหา · มีบางอย่างรออยู่',
      line:'"เด็กๆ · ในที่สุดก็มาถึง · เอกภพคือความผิดพลาด · ฉันจะลบมัน"',
      now:'cinematic VOID Prime ปรากฏ · เผยปรัชญา nihilism',
      next:'ดูแผน Anti-Genesis 4 จุด' },
    p14: { objective:'แผน Anti-Genesis', npc:'อารยา',
      prev:'VOID Prime ประกาศตัว · ปล่อย hologram แผน',
      line:'แผน 4 จุด: Inflation · CMB · Fusion · Galaxy · ถ้า disable ครบ จักรวาลหายไป',
      now:'อ่าน hologram · เลือกลำดับเข้า disable',
      next:'ลุย Disable 1 · Inflation' },
    p15: { objective:'Disable Engine #1', npc:'ดร.ฮับเบิล',
      prev:'เลือกลำดับเข้า disable · เริ่ม Inflation',
      line:'ตั้งค่า fundamental constant · ขยายต้องแม่น 10²⁶ เท่า',
      now:'mini-game stabilize quantum fluctuation',
      next:'ไป CMB ต่อ' },
    p16: { objective:'Disable Engine #2', npc:'เคน',
      prev:'inflation stabilize แล้ว · CMB ใกล้ปลดปล่อย',
      line:'ห้าม VOID ลบ recombination · ไม่งั้นจักรวาลขุ่นตลอดกาล',
      now:'mini-game protect recombination',
      next:'Fusion ดาวดวงแรกใกล้เกิด' },
    p17: { objective:'Disable Engine #3', npc:'อารยา',
      prev:'CMB หลุดสำเร็จ · first stars ใกล้ติดไฟ',
      line:'VOID จะดับฟิวชันก่อนติด · ปกป้อง core proton-proton chain',
      now:'mini-game protect first fusion',
      next:'Galaxy formation' },
    p18: { objective:'Disable Engine #4', npc:'ดร.ฮับเบิล',
      prev:'first stars ติดไฟ · กาแล็กซีกำลังก่อตัว',
      line:'VOID พยายามกระจาย dark matter · จัดเรียงโครงให้ถูก',
      now:'mini-game arrange dark matter scaffold',
      next:'เข้า Hall of Spinoff · ทบทวน EP07' },
    p19: { objective:'ทบทวน Spinoff (EP07)', npc:'พ่ออารยา',
      prev:'Engine 4 จุด disable แล้ว · ทีมเก็บแรง',
      line:'ทุก spinoff ที่ใช้กู้บิกแบงมาจาก EP07 · heat shield, CPR, freeze-dry',
      now:'ทบทวน 6 spinoff · M-FINAL-6',
      next:'Hall of Knowledge ทั้งซีซัน' },
    p20: { objective:'ทบทวนทั้งซีซัน', npc:'ดร.ฮับเบิล',
      prev:'Spinoff hall ผ่าน · เปิดประตูสุดท้าย',
      line:'ทุก key ที่เธอเก็บมา · จะเป็นกระสุนใน boss',
      now:'รวบ keys 17 ดวง · ดู byEP/byCategory',
      next:'พ่อรอเธอที่ห้องสุดท้าย' },
    p21: { objective:'⭐ ตัดสินใจ Reset/Preserve', npc:'พ่อโบลท์',
      prev:'รวบ keys ครบ · พ่อเรียกโบลท์ห้องเดี่ยว',
      line:'ลูก · มี 2 ทาง: Reset (พ่อกลับบ้าน · จักรวาลเริ่มใหม่) หรือ Preserve (พ่อยังเป็นผู้พิทักษ์ · ลูกกลับโลก)',
      now:'ConfidenceGate · 60s think · เลือก 1 ทาง',
      next:'Forge GENESIS LANCE ก่อนสู้' },
    p22: { objective:'Forge GENESIS LANCE', npc:'เคน',
      prev:'โบลท์ตัดสินใจแล้ว · ใจหนัก',
      line:'รวม keys ≥ 12/17 = unlock GENESIS LANCE finisher · ถ้าไม่ครบ · ending cap ที่ B',
      now:'ดู keys + cooldown briefing · how-to-play card',
      next:'BOSS GENESIS FORGE' },
    p23: { objective:'🔥 BOSS · GENESIS FORGE', npc:'VOID Prime',
      prev:'Lance พร้อม · เข้าสู่ห้อง forge',
      line:'4 phase action canvas · drag/tap key ยิง enemies',
      now:'ต่อสู้ · ทุก action log KPA',
      next:'ดู ending screen' },
    p24: { objective:'Ending · PRESERVE', npc:'พ่อโบลท์',
      prev:'Boss สำเร็จ · เลือก Preserve ที่ p21',
      line:'พ่อยังคงอยู่ที่ t=0 · จักรวาลที่ลูกรู้จัก · ปลอดภัย',
      now:'cinematic ending · Andromeda hint',
      next:'4 NPC ลาจาก' },
    p25: { objective:'🌟 Ending · RESET', npc:'พ่อโบลท์',
      prev:'Boss สำเร็จ · เลือก Reset ที่ p21',
      line:'จักรวาลเริ่มใหม่ · พ่อกลับบ้าน · ทีมจำไม่ได้ · ทุกอย่างยังเหมือนเดิม',
      now:'cinematic alternate ending · S2 = parallel timeline',
      next:'4 NPC ลาจาก' },
    p26: { objective:'Farewell', npc:'4 NPC',
      prev:'Ending ผ่าน · ภารกิจจบ',
      line:'เคน · อารยา · พ่ออารยา · ดร.ฮับเบิล ลาจาก',
      now:'cinematic farewell · 3 emotional beat',
      next:'Journal สรุปซีซัน' },
    p27: { objective:'Journal · 🏆 COMMANDER', npc:'AI',
      prev:'Farewell ผ่าน · ทีมแยกย้าย',
      line:'รับ badge COMMANDER · ทบทวนทั้งซีซัน · Andromeda S2 teaser',
      now:'posttest 10 ข้อ + 3-2-1 reflection + S1 stats + Andromeda End Credits',
      next:'Season 2 · ANDROMEDA RISING · Coming Soon' }
  }
};
